### ISSUE TITLE
Suggestion for UI first screen

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#1]
- On the first screen it is not clear that there are 4 articles instead of two. 
- Suggestion add a ledger on the right so that you can there are more articles OR make buttons out of it?
- The term/title under the card picture is 'order your cards' but that doesnt say anything/doesnt give instructions about the articles below. 
- Suggestion instead of bold text 'order your cards' normal text something like: You can go to the next step in ording your cards by using the button below. In the articles below you will find more information.
- Suggestion change text of the blue button to 'Order your cards' or 'Order now' or 'Order here!' or 'Order your cards here!'

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/dc05adea-08f9-4d73-ab39-f8da6cbae8e4)

**Comment by KevinKoobs** [comment]
Close as won't fix after conversation with Tom
