### ISSUE TITLE
Unclear the you have to scroll down to fill in more information on order screen

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#10]
On the order screen it is unclear (no visual clues) that you have to scroll down to fill in more information to be able to continue to payment.

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/160817dd-31f2-4cb2-91ed-728accaa4962)

**Comment by KevinKoobs** [comment]
Agreed, I'm going to look for a arrow or something

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/f18e8fbb9cd0e2aef2f0ff8f668114132ab7dc5f
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/10497513/868f0c2c-f6e4-4f96-ba4a-b78f60dc63a4)
