### ISSUE TITLE
Cover account reserve for on card

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#11]
Nor the text nor the ? text doesnt answer the 'Why question' why someone would add prepaid XRP.

Could be on purpose but I wanted to address it.

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/f88af44fcd42dc36fb53bc14e1a1894bd9ad0e97

Note: The text 'here' points to the new article, but is only visible if you don't want to cover account reserve
