### ISSUE TITLE
Auto selecting Country and changing country very small /not a button?

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#12]
For the 'where to buy XRP'  xApp your country is preselected based on IP (i think). That something I would like to see here as well!

After selecting a country, to change the 'change the country' option is not a button and it is pretty small.

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/705e29bb-9fb3-4c38-85e6-6954d1c6bdf4)

**Comment by KevinKoobs** [comment]
Country pre selection would be a nice to have in a future release. 

Button stays this way because it's a tertiary one and doesn't need that much attention. Just be careful when selecting your country 😛 
Just Kidding: this is the design system
