### ISSUE TITLE
When selecting a country: after typing the first 2 letters the results are incorrect 

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#13]
On the order screen, when selecting a country , after typing the first 2 letters the country results are incorrect:
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/8e986a1d-7962-4c0e-9d6b-5dd2d91ac18e)

e.g. when typing NE it doesnt show netherlands.

I would consider this a minor issue

**Comment by KevinKoobs** [comment]
@tomxrpllabs It does when you scroll down. The filter is not 'starts with', but 'has'. All those countries have 'ne' in them, so they show up.

For now I'll leave this alone; this is a default implementation from Tailwind UI, I don't have the knowledge yet to fix it if I want to
