### ISSUE TITLE
pre payment 'address' screen feedback

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#14]
The pre-payment 'address' screen is not really an address screen more of a name/contact info screen.

- The email address field is just a text field not a email address field css wise (see keyboard)
- The keyboard goes over the button on my phone (Samsung Galaxy S21 FE 5G)

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/1748586c-34e4-4e0d-a55e-ad286eeb7301)

**Comment by KevinKoobs** [comment]
The title states "Please fill in your name and email address" ;)

I've updated the email field in https://github.com/XRPL-Labs/xBuyTangem/commit/5b256a6994d602d23c5f7a74bbbd91fcfa4e9b65
I've tried to fix the issue with the button in https://github.com/XRPL-Labs/xBuyTangem/commit/7279fe48ea35ac44960164bc7537078dc3821b30

Note: the buttons now stay behind the keyboard on purpose

**Comment by tomxrpllabs** [comment]
Im now stuck in an Oh no, an error has occurred message without error code. 

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/82ed3baa-30b0-47a1-af24-1fac4a1dbdcd)
