### ISSUE TITLE
Errors after selecting klarna but not continuing

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#15]
30001
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/aa8dda02-dc4f-4ba1-89bb-46b8c199b3eb)

after restart Xumm:
credit cardNan?
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/e725128e-14d9-41fd-b95e-10267cbf33de)

10007 error
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/5461923f-e3f0-4658-b758-fc959b4a0937)

**Comment by KevinKoobs** [comment]
Can't reproduce right now
