### ISSUE TITLE
Klarna payment screen 'sticks' to the top of the screen

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#16]
After selecting Klarna on the payment screen the next Klarna payment screen 'sticks' to the top of the screen. It is also in dutch which if fine but the rest was in english.

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/105b267a-8928-4b34-9526-d4e7e0a0637d)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/249977aa6813384a13539e6483a3b53850bdd47f

Note: Klarna will always be on the bottom, even when you focus. There is no quick fix for that right now

**Comment by tomxrpllabs** [comment]
Please look at the printscreen the first field is not in view
