### ISSUE TITLE
White screen after failed klarna setup

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#17]
White screen after failed klarna setup:

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/8f086ef7-455e-4a3c-a1d3-94c7c68c15c4)

I tried to setup klarna but my phone number got declined (probably because Im trying to use GBP), after being declined I dont go back to order screen but go to a white screen instead.

**Comment by KevinKoobs** [comment]
Can't reproduce right now
