### ISSUE TITLE
Apple pay shown twice?

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#18]
may be a little double up (dutch joke) to show apple pay twice?

<img width="403" alt="image" src="https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/534b6ab5-8307-43df-8e7d-d01e486a8e9b">

**Comment by KevinKoobs** [comment]
True, that's the way Stripe works unfortunately. But I'll hack something together :)

**Comment by KevinKoobs** [comment]
Never mind.. The hack isn't working, so I'll leave it for now
