### ISSUE TITLE
Stop mentiong (Tangem) everywhere.

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#2]
This is a good time/place to stop using (Tangem) everywhere and start using the term Xumm Cards.

**Comment by WillXUMM** [comment]
I agree. This is probably a good time. Tangem just released v2.0 of their card which does not work in Xumm. Differentiating will help us in support.  If we change though, we should update the name of the Tangem Backup xApp to something like "Xumm Card Backup" and it will need to be updated.

...and I'll need to update all the articles.  Let me know so I can get started.

**Comment by KevinKoobs** [comment]
@WillXUMM We will remove 'Tangem' from all of our outings, so I start with the xApp now :)
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/a454893ffe5446d45841e67b61adaf48d64551cc
