### ISSUE TITLE
After payment with Xumm i went back to payment screen?

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#20]
After payment with Xumm:
https://livenet.xrpl.org/transactions/5761A447715F458B5307174C6CEFBDBAAEAF549849990422D433D97AB14D0367

I went back to payment screen and I didnt get an order confirmation on screen NOR by email.

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/1ff1e436-776f-4d6c-a1d0-a56f865e1e89)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/accdb98bd42f24d47e2d6fe7d78cea24f4eec9c4
