### ISSUE TITLE
Submit order button isnt working

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#22]
after filling in all the information in the fields and pressing the submit order nothing happens

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/b4420a6e-7763-4863-a34e-6b74b1838276)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/85a5592111b2a45dbd2608c2be39ffce9de4e902
