### ISSUE TITLE
Pressing submit order doesnt respond

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#23]
Testing wiht Iphone and different r-address. On the get cards address screen I filled in all information, the submit order button doesnt repsond.

**Comment by tomxrpllabs** [comment]
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/5746c216-d9c7-4842-bc08-8dcfd0e61831)

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/e285853d-84ce-4a69-a75e-a523ff2098c7)

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/f8dca4ec-68d0-413a-bfa8-2a6cea695cb3)

**Comment by tomxrpllabs** [comment]
interesting AFTER closing and switching to other account and than switching back to this account and opening xApp and conitnueing the flow, the telephone number field is empty. The rest of the field are still filled

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/cd295298-feff-4093-861b-7088c3f30ccc)

**Comment by KevinKoobs** [comment]
Fixed in [85a5592111b2a45dbd2608c2be39ffce9de4e902](https://github.com/XRPL-Labs/xBuyTangem/commit/85a5592111b2a45dbd2608c2be39ffce9de4e902)
