### ISSUE TITLE
name and email fields in credit card payment flow

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#24]
repro:
After selecting credit card option you get the fill in page below
The name and email fields are blob/text fields and they could be field typed accordingly

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/94df8ba3-4b05-4cd4-bb3e-e961e12ac225)

**Comment by KevinKoobs** [comment]
Fixed
