### ISSUE TITLE
It is cheaper to buy cards with CC?

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#25]
It seems that using Xumm is more expensive than credit card now ;)

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/d2083bea-e85e-47d2-b6fa-4d4a1afc74fd)

real price is around 69 eur
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/445f445a-94f8-4646-b3fb-669f7bd77a9e)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/a62195230764e49b62cf95dbacb5da25a74c4ce3
