### ISSUE TITLE
xApp doesnt follow light/dark mode?

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#3]
If got Xumm in dark mode but the xApp is light, but the notice when you want to open an URL is in dark mode again.

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/32b88d10-3990-4758-bff7-4b88518aa3a9)

**Comment by KevinKoobs** [comment]
That's true; we don't support any theme yet, but the popup you see is Xumm native so it follows the theme you've chosen
