### ISSUE TITLE
Variable instead of value in help text

### ISSUE THREAD

**Issue by NetScr1be** [KevinKoobs/xBuyTangem-issues#5]
### Issue Description

In the _Get Cards_ > _Xumm Card Properties_ the variable `$(props.token)` appears instead of the intended text (network name?).

See attached screenshot:

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/5115007/7363942d-63ab-404c-b8a6-078ad4930ad4)

### Steps to reproduce

1. Open xApp
2. Select _Order Cards_
3. Scroll down to then select  _Xumm Card Properties_

### Error Messages

N/A

### Account Address

- rpGhdshAMiVYPei3FtusVTPndijbpdATna

### Device Info

- Pixel 6 Pro
- Android 14 (Build UP1A.231005.007)

**Comment by NetScr1be** [comment]
Is the variable name supposed to be meaningful?

**Comment by KevinKoobs** [comment]
No it's not, it's code that should have been executed but didn't because of quotes ;P

Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/6bdb3ded4a19109bc6faf0a730aeff960c42f1e2
