### ISSUE TITLE
Total price unclear

### ISSUE THREAD

**Issue by NetScr1be** [KevinKoobs/xBuyTangem-issues#6]
### Issue Description

The line item prices and total don't match.

Even before the _Shipping Country_ was selected the _Total_ was ($CAD?) $104.

Selecting the country (Canada) did not change the total

N.B. Xumm Default Currency = CAD

| Category | Card Price | Reserve Coverage | Shipping | Total |
| --- | --- |  --- | --- | --- | 
| Actual | $41 | $8.71 | $41 | $89.71 |
| App | $41 | $8.71 | $41 | $103.89 |

### Steps to Reproduce

1. Open xApp
2. Select Order Cards
3. Select Quantity
4. Select Reserve Coverage

![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/5115007/588f330c-3bd3-4061-95af-5b66a2ed086a)

### Error Messages

N/A

### Account Address

rpGhdshAMiVYPei3FtusVTPndijbpdATna

### Device Info

- Pixel 6 Pro
- Android 14 (Build UP1A.231005.007)

**Comment by KevinKoobs** [comment]
In the calculation, you're missing the 15 XRP you've added to your card. With the rounding in the small pills (hence the ~ sign) the amount adds up again

**Comment by KevinKoobs** [comment]
As constructed with Patrick: The problem lies in the fact that the ~ $ 8.75 is not updating when you change the amount of spendable XRP. So I'm going to change that.

**Comment by KevinKoobs** [comment]
Will be fixed in #7
