### ISSUE TITLE
Price of Reserve Coverage doesn't change

### ISSUE THREAD

**Issue by NetScr1be** [KevinKoobs/xBuyTangem-issues#7]
### Issue Description

Reserve Price estimate does not change to match selected option.

The total price updates but not the item price.

Screenshots: https://photos.app.goo.gl/54UJWQ34nijt3r6EA

### Steps to Reproduce

1. Open xApp
2. Select Order Cards
3. Select Quantity
4. Select Reserve Coverage

### Error Messages

N/A

### Account Address

rpGhdshAMiVYPei3FtusVTPndijbpdATna

### Device Info

- Pixel 6 Pro
- Android 14 (Build UP1A.231005.007)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/b31582400b74acedbe96791c2371bebe3fd894c2
