### ISSUE TITLE
Payment screen

### ISSUE THREAD

**Issue by tomxrpllabs** [KevinKoobs/xBuyTangem-issues#9]
- Different font (not sure) and font size compared to previous screens
- text doesnt fully fit on the page, cant scroll so can't read the last line
- back 'button' is not what we normally use 
- 
![image](https://github.com/KevinKoobs/xBuyTangem-issues/assets/96502472/cbe2c6ee-08d3-4d19-b906-a974241a2056)

**Comment by KevinKoobs** [comment]
Font and scrolling will be fixed!

Back button is our tertiary button and in this case the only button I could use because the other two are already used ;)

**Comment by KevinKoobs** [comment]
Fixed in https://github.com/XRPL-Labs/xBuyTangem/commit/29771bb4cda7a80ee28d8a91950d944fc2d5a358
